name: Update the json with the latest anime charts
on:
    push:
        branches:
            - master
    schedule:
        - cron: '0 0,6,12,18 * * 5'
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout the repository
              uses: actions/checkout@v4.1.2
            - name: Setup Python
              uses: actions/setup-python@v5.1.0
              with:
                python-version: '3.10'
            - name: Python Dependency Installation
              uses: py-actions/py-dependency-install@v4

            - name: Run the python scripts
              run: |
                python3 src/animecorner.py
            - name: Commit the changes
              run: |
                git config --local user.name 'infernalsaber'
                git config --local user.email '72517486+infernalsaber@users.noreply.github.com'
                git commit -am "Scheduled update"
                git push
